hmcts/sscs-track-your-appeal-notifications

README.md, docker-compose.yml, src/main/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializer.java, src/main/java/uk/gov/hmcts/sscs/domain/CcdResponse.java, src/main/java/uk/gov/hmcts/sscs/domain/Subscription.java, src/main/java/uk/gov/hmcts/sscs/domain/notify/NotificationType.java, src/main/java/uk/gov/hmcts/sscs/domain/notify/Personalisation.java, src/main/java/uk/gov/hmcts/sscs/factory/NotificationFactory.java, src/test/java/uk/gov/hmcts/sscs/controller/NotificationControllerTest.java, src/test/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializerTest.java, src/test/java/uk/gov/hmcts/sscs/factory/NotificationFactoryTest.java
- Receive callbacks from CCD
- Map CCD fields to Notification Subscriptions correctly
- Receive an Appellant and Supporter Notification details
- Ignore Supporter, assume notification is only sent to Appellant for MVP
- Updated Readme to provide instructions on debugging CCD callbacks with Notifications
=> SSCS-2575 Unblock CCD callbacks to Notifications

src/main/java/uk/gov/hmcts/sscs/TrackYourAppealNotificationsApplication.java, src/main/java/uk/gov/hmcts/sscs/config/AppConstants.java, src/main/java/uk/gov/hmcts/sscs/config/NotificationConfig.java, src/main/java/uk/gov/hmcts/sscs/domain/notify/Personalisation.java, src/main/java/uk/gov/hmcts/sscs/placeholders/AppealReceivedPersonalisation.java, src/main/resources/config/application.properties
- Add missing fields to allow an appeal received email to be sent to Gov Notify
- Hardcoded values which are dependent on other stories and added TODOs
=> SSCS-2576 Send Notification to gov notify

src/main/java/uk/gov/hmcts/sscs/personalisation/Personalisation.java, src/test/java/uk/gov/hmcts/sscs/personalisation/PersonalisationTest.java, src/test/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisationTest.java, src/test/java/uk/gov/hmcts/sscs/service/MessageAuthenticationServiceImplTest.java
- Set Appeal respond date, Evidence received date and Hearing contact date based on the type of the latest Event
=> SSCS-2743 Add event date to Personalisation

src/IntegrationTests/resources/json/ccdCallbackResponse.json, src/main/java/uk/gov/hmcts/sscs/config/AppConstants.java, src/main/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializer.java, src/main/java/uk/gov/hmcts/sscs/domain/Benefit.java, src/main/java/uk/gov/hmcts/sscs/domain/CcdResponse.java, src/main/java/uk/gov/hmcts/sscs/personalisation/Personalisation.java, src/test/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializerTest.java, src/test/java/uk/gov/hmcts/sscs/factory/NotificationFactoryTest.java, src/test/java/uk/gov/hmcts/sscs/personalisation/PersonalisationTest.java, src/test/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisationTest.java
- Extract the benefit code and description from the CCD response
- Use this to create the benefit type used in the subject line of most notifications
=> SSCS-2930 Notification benefit type

src/IntegrationTests/java/uk/gov/hmcts/sscs/tya/NotificationsIt.java, src/IntegrationTests/resources/json/ccdCallbackResponse.json, src/main/java/uk/gov/hmcts/sscs/domain/notify/EventType.java, src/main/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisation.java, src/main/java/uk/gov/hmcts/sscs/service/NotificationService.java, src/main/resources/config/application.properties, src/test/java/uk/gov/hmcts/sscs/factory/NotificationFactoryTest.java, src/test/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisationTest.java, src/test/java/uk/gov/hmcts/sscs/service/NotificationServiceTest.java
- When an email address subscription is changed then send a confirmation email to the new email address
- Do not send emails or texts when relevant subscription flags are set to false
=> SSCS-2701 Send change subscription details email

src/main/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisation.java, src/test/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisationTest.java
This PR fixes this edge case:
1. Latest event on a case is Appeal Dormant
2. It has no subscriptions
3. User adds a new subscription 
4. Notification service tries to find the latest event. In this case it is appeal dormant but notification service doesn't know about this case (as no notifications for appeal dormant)
5. Blows up with a null pointer
=> Fix exception thrown when notification type not known

src/IntegrationTests/resources/json/ccdCallbackResponse.json, src/main/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializer.java, src/main/java/uk/gov/hmcts/sscs/domain/CcdResponse.java, src/main/java/uk/gov/hmcts/sscs/domain/reminder/Action.java, src/main/java/uk/gov/hmcts/sscs/domain/reminder/Reminder.java, src/test/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializerTest.java, src/test/java/uk/gov/hmcts/sscs/factory/NotificationFactoryTest.java, src/test/java/uk/gov/hmcts/sscs/personalisation/PersonalisationTest.java, src/test/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisationTest.java, src/test/java/uk/gov/hmcts/sscs/service/ReminderServiceTest.java
- When deserialising case from CCD extract the caseId so that this can be used be Reminders
- Change field names for Reminder object to match Tribunals API
=> SSCS-2704 Extract caseId

src/main/java/uk/gov/hmcts/sscs/deserialize/CcdResponseWrapperDeserializer.java, src/main/java/uk/gov/hmcts/sscs/personalisation/SyaAppealCreatedPersonalisation.java, src/test/java/uk/gov/hmcts/sscs/personalisation/SyaAppealCreatedPersonalisationTest.java
Issues fixed: 
- Language interpreter threw NPE when missing
- Missing representative set fields to null in the email
- Missing MRN details set fields to null in the email
=> Fix appeal created email issues

src/main/java/uk/gov/hmcts/sscs/personalisation/SyaAppealCreatedPersonalisation.java, src/test/java/uk/gov/hmcts/sscs/personalisation/SyaAppealCreatedPersonalisationTest.java
The 'reason for appeal' and 'appeal description' appeared in the wrong order on the Appeal Created summary email, so just switched them around
=> Switch appeal reason and description

src/e2e/java/helper/EnvironmentProfileValueSource.java, src/e2e/java/helper/FunctionalTestHelper.java, src/e2e/java/uk/gov/hmcts/sscs/functional/NotificationsFunctionalTest.java, src/e2e/java/uk/gov/hmcts/sscs/functional/ReminderNotificationsFunctionalTest.java, src/main/java/uk/gov/hmcts/sscs/service/ccd/SearchCcdService.java
Mock the CCD response for the Appeal Received functional test. 
This is an attempt to solve the issue of CCD callbacks pointing to the preview environment, meaning testers could be testing old code if using AAT (Issue described in SSCS-3655 ticket)
=> SSCS-3655 Mocked functional test

src/IntegrationTests/java/uk/gov/hmcts/sscs/tya/HearingHoldingReminderIt.java, src/IntegrationTests/java/uk/gov/hmcts/sscs/tya/NotificationsIt.java, src/e2e/java/uk/gov/hmcts/sscs/functional/AbstractFunctionalTest.java, src/e2e/java/uk/gov/hmcts/sscs/functional/ReminderNotificationsFunctionalTest.java, src/e2e/resources/hearingBookedCallback.json, src/main/java/uk/gov/hmcts/sscs/service/NotificationService.java, src/main/java/uk/gov/hmcts/sscs/service/NotificationValidService.java, src/test/java/uk/gov/hmcts/sscs/CcdResponseUtils.java, src/test/java/uk/gov/hmcts/sscs/service/NotificationServiceTest.java, src/test/java/uk/gov/hmcts/sscs/service/NotificationValidServiceTest.java
- Notifications were still being sent for hearings that had already happened. This fixes this
=> SSCS-3771 Fix for past hearing booked notifications sent

infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/variables.tf, src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/config/NotificationConfig.java, src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/factory/NotificationFactoryTest.java, src/test/java/uk/gov/hmcts/reform/sscs/personalisation/CohPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/sscs/personalisation/SubscriptionPersonalisationTest.java
When an appellant's questions have expired a callback is made from COH
to the /coh-send endpoint. This will contain the event type
question_deadline_elapsed and will trigger notifications to be sent to
the appellant.
=> [PREVIEW] SSCS-3790 Notify appellant that their questions have expired

infrastructure/main.tf
In a few words: we currently use a service plan for application. After the change, we will have a single plan per project.
While we currently have a 1:1 mapping between applications and compute resources, with a shared plan we can fit more apps into a single compute resource.
The change is rolled out in two stages.
1. Explicitly enable the app service plan in Terraform
1. Switch the service plan to use a shared service plan.
**PLEASE NOTE, THIS PR IS FOR STEP 1 ONLY**
More info on the change: https://tools.hmcts.net/confluence/display/CNP/Migrate+to+Shared+App+Service+Plan (please note that the instructions are for the full migration).
=> Use app service plan

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/CohNotificationsIt.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/AbstractFunctionalTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/CohNotificationFunctionalTest.java, src/main/java/uk/gov/hmcts/reform/sscs/factory/NotificationFactory.java, src/main/java/uk/gov/hmcts/reform/sscs/personalisation/CohDateConverterUtil.java, src/main/java/uk/gov/hmcts/reform/sscs/personalisation/CohPersonalisation.java, src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java, src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java, src/main/java/uk/gov/hmcts/reform/sscs/service/coh/QuestionService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/SscsCaseDataUtils.java, src/test/java/uk/gov/hmcts/reform/sscs/personalisation/CohDateConverterUtilTest.java, src/test/java/uk/gov/hmcts/reform/sscs/personalisation/CohPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/coh/QuestionServiceTest.java
If the online panel issue more questions after the first round we do not
want the notifications to be the same. Changed the logic to select a
template based on the notification event and the current question round.
=> [PREVIEW] SSCS-3788 Send different notifications for follow up rounds of questions

src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/NotificationEventType.java, src/main/resources/application.yaml
Add a notification that the panel has decided the appellant will need to
attend a hearing.
This is triggered by a continuous_online_hearing_relisted notification
from COH.
=> SSCS-3546 Notify appellant a hearing is required

infrastructure/aat.tfvars, infrastructure/preview.tfvars
This might be bacause gov notify expects links to start with https and
we have not been setting this for real yet so was http.
=> SSCS-3974 Fix links in texts

dependency-check-suppressions.xml
version of slf4j but the latest release is only beta and has a bug where
it does not log anything.
=> Suppress CVE-2018-8088. This is a security issue with the current

build.gradle
This is meant to solve the following error:
```
One or more dependencies were identified with known vulnerabilities:
c3p0-0.9.5.2.jar (com.mchange:c3p0:0.9.5.2, cpe:/a:mchange:c3p0:0.9.5.2) : CVE-2018-20433
```
=> Upgraded dependency for c3p0

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/OutOfHoursIt.java, src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
- When a case contains multiple subscriptions and it is out of hours, then only schedule one notification event to be triggered in hours
=> SSCS-5057 Stop duplicate notifications

infrastructure/demo.tfvars, infrastructure/preview.tfvars, kubernetes/deployment.template.yaml
Links to COR in notifications were to the staging slot not prod in demo. Adding this back to master and merging in other changes I think we need from the master branch.
=> Set online_hearing_link to be the respective prod slot not the staging slot.

build.gradle
```
Caused by: java.lang.NoSuchMethodError: feign.Request.httpMethod()Lfeign/Request$HttpMethod;
at feign.httpclient.ApacheHttpClient.toHttpUriRequest(ApacheHttpClient.java:91)
at feign.httpclient.ApacheHttpClient.execute(ApacheHttpClient.java:81)
at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97)
at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
at com.sun.proxy.$Proxy138.getServiceName(Unknown Source)
at uk.gov.hmcts.reform.sscs.service.AuthorisationService.authorise(AuthorisationService.java:26)
at uk.gov.hmcts.reform.sscs.controller.NotificationController.sendNotification(NotificationController.java:50)
```
=> feign-httpclient upgrade does not work. Downgrade it back again.

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java, src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java, src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java, src/test/resources/json/ccdResponseWithNoOldCaseRef.json
- When the SC number was a Scottish number and the RPC was unknown, then a NPE was throw when building the RPC personalisation details
=> SSCS-5217 RPC NPE fix for scottish SC numbers

dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/service/scheduler/BaseActionExecutor.java
If we run an action and it fails we currently can't always tell which
case it was associated with. Add a log statement in the base action
executor to log the case id for any exceptions thrown in the
ActionExecutor.
=> SSCS-5383 Log errors when actions fail

src/main/resources/db/migration/V20190508_02__reminders-removal.sql
SSCS-5395 Remove DWP late reminders from Quartz
```
[ ] Yes
[ ] No
```
=> SSCS-5380 Remove hearing holding reminders from Quartz

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceForSubscriptionUpdatedTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/CohNotificationsIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/OutOfHoursIt.java, src/main/java/uk/gov/hmcts/reform/sscs/service/BundledLetterTemplateUtil.java, src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/service/BundledLetterTemplateUtilTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/SendNotificationServiceTest.java
When we send a bundled letter, either struck out or direction issued we
need to use a different template for the letter sent to the the
representative. These templates have been added to sscs-pdf-email-common
and need to be selected for use.
https://tools.hmcts.net/jira/browse/SSCS-5512
```
[ ] Yes
[X] No
```
=> SSCS-5512 Bundled Rep letters

src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java, src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
When we send an email to a user saying they have question to be answered
by the panel, we send them a link to register on COR. This will become
MYA and they will need a TYA number to be included in the url.
Format for new url
http://{domain}/register?tya=XXXXXXXXX
```
[ ] Yes
[ ] No
```
=> SSCS-5806 Add TYA id to the COR register link

src/main/java/uk/gov/hmcts/reform/sscs/config/NotificationConfig.java, src/main/java/uk/gov/hmcts/reform/sscs/factory/NotificationFactory.java, src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java, src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
https://tools.hmcts.net/jira/browse/SSCS-6625
directionIssued letter is not being sent when benefit type doesn’t exist
```
[ ] Yes
[X] No
```
=> SSCS-6625 - Allow blank/empty benefit types (edge case)

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ReminderNotificationsFunctionalTest.java
Temporary disable reminder tests to try and force code through to AKS. I think the tests are picking slots that don't have the code deployed to them so hopefully this resolves the issue.
=> Temporay disable reminder tests

src/test/java/uk/gov/hmcts/reform/sscs/service/LetterUtilsTest.java
We are getting random test failures - looks like the same object was being used in tests after it has been used in other tests. Sometimes they were passing, sometimes failing. This PR should fix the issue.
=> Fix random test failure - looks like same object is getting changed

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/JointPartyFunctionalTest.java, src/e2e/resources/jointParty/directionIssuedCallback.json, src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapper.java, src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java, src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
SSCS-7953 - Directions - Appeal to Proceed for Joint Party
Added "joint_party" to 'Yes' when the subscription type is for a joint party
Modified existing template for a joint party
An example letter for direction issued - appeal to proceed is [here](https://www.notifications.service.gov.uk/services/cf23bf9c-4a42-42d1-a734-5cfc53dda6ca/notification/1801e2c2-0c52-4bf3-9b3b-ec313b95c39a)
=> SSCS-7953 - Directions - Appeal to Proceed for Joint Party

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/SSCS-7937
Migrating joint party paper upload response sms template to its own version, with custom text
```
[ ] Yes
[x] No
```
=> Sscs 7947 upload response joint party paper sms fix

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ReminderNotificationsFunctionalTest.java
Ignore failing test
undo this PR once all the apps in AAT have are running the latest code. We have two apps running on two clusters, we have this for staging and non-staging. The reminders might get sent from the non-staging apps that do not have the new sms/email configurations.
=> Ignore failing test

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10166
poi and opencvs versions are updated in sscs-common and sscs-pdf-email-common as the security vulnerabilities they have are preventing feature developments
```
[X] Yes
[ ] No
```
=> SSCS-10166-Upgrade/Fix poi and commons-beanutils vulnerabilities

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/AdminAppealWithdrawnNotificationsTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/DocmosisWithGovNotifyLetterFunctionalTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/EvidenceReceivedFunctionalTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/JointPartyFunctionalTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/NotificationsFunctionalTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/OtherPartyFunctionalTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/WelshNotificationsFunctionalTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/WithRepresentativePersonalisationTest.java
Reverts hmcts/sscs-track-your-appeal-notifications#2452
=> Revert "Disable functional tests as notifications are not sent out of hours"

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCSCI-769
- Updated sscs-common to 5.3.4
- Removed CVE-2024-25710 because that was coming from sscs-common.
=> Update sscs-common to 5.3.4

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCSCI-845
Updated snakeyaml from 1.33 to 2.0 to fix CVE-2022-1471
Removed CVE-2024-1597 from suppressions as postgresql is already upgraded to latest available version (42.7.3)
=> Upgrade snakeyaml to 2.0 - CVE-2022-1471

src/main/java/uk/gov/hmcts/reform/sscs/config/LetterAsyncConfigProperties.java, src/main/java/uk/gov/hmcts/reform/sscs/service/SaveCorrespondenceAsyncService.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/SSCSSI-331 
- Setting maxDelay as the default is 30 seconds if unspecified thus limiting the overall time for retries to just under 2 minutes.
- Nearly 7%  of the PDFs are not ready by then, tuning maxRetries, delays and multiplier to wait for a maximum of15 minutes.
- Also adding initialDelay for first attempt with Thread.sleep as first attempt is always failing. 
- Alternative approach to handle Thread.Sleep will be something like, but we cannot avoid the Thread from waiting to continue further.
```Java
if(context != null && context.getRetryCount() == 0){
log.info("adding additional wait");
ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor();
try {
CompletableFuture<Void> delayedFuture = CompletableFuture.runAsync(() -> …
```
=> SSCSSI-331 | Add initial delays and maxdelay for async corresponding processing

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java, src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-830
Notifications messages dwp due date should be set as: 
- Child Support cases should be calculated as 'Sent to FTA' event's date plus 42 days
- All other case types as plus 28 days
=> SSCSCI-830 - Dwp Response Date Notifications

Jenkinsfile_CNP, Jenkinsfile_nightly
Currently Jenkins logs contributes the most logs as all functional test and possibly unit/integration test logs are being shipped every time a build is run.
App should still get the key from  https://github.com/hmcts/sscs-track-your-appeal-notifications/blob/master/charts/sscs-tya-notif/values.yaml#L46
=> Remove Jenkins logs being shipped to appinsights
