hmcts/sscs-track-your-appeal-notifications

build.gradle
src/IntegrationTests/java/uk/gov/hmcts/sscs/tya/NotificationsIt.java
src/IntegrationTests/resources/json/ccdCallbackResponse.json

- Add an integration test for each of the Notification types which have been implemented so far

SSCS-2654 Add Integration Tests

---

src/IntegrationTests/java/uk/gov/hmcts/sscs/tya/NotificationsIt.java
src/main/java/uk/gov/hmcts/sscs/config/AppConstants.java
src/main/java/uk/gov/hmcts/sscs/domain/notify/NotificationType.java
src/main/java/uk/gov/hmcts/sscs/factory/PersonalisationFactory.java
src/main/java/uk/gov/hmcts/sscs/placeholders/Personalisation.java
src/main/java/uk/gov/hmcts/sscs/placeholders/PostponementPersonalisation.java
src/main/resources/config/application.properties
src/test/java/uk/gov/hmcts/sscs/factory/PersonalisationFactoryTest.java
src/test/java/uk/gov/hmcts/sscs/placeholders/PostponementPersonalisationTest.java
src/test/java/uk/gov/hmcts/sscs/service/NotificationServiceTest.java

SSCS-2709 Hearing Postponed Notification

---

src/IntegrationTests/java/uk/gov/hmcts/sscs/tya/NotificationsIt.java
src/main/java/uk/gov/hmcts/sscs/domain/notify/NotificationType.java
src/main/resources/config/application.properties

SSCS-2711 Appeal Withdrawn Notification

---

build.gradle
dependency-check-suppressions.xml
src/IntegrationTests/resources/json/ccdCallbackResponse.json
src/main/java/uk/gov/hmcts/sscs/TrackYourAppealNotificationsApplication.java
src/main/java/uk/gov/hmcts/sscs/controller/NotificationController.java
src/main/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializer.java
src/main/java/uk/gov/hmcts/sscs/domain/CcdResponse.java
src/main/java/uk/gov/hmcts/sscs/domain/CcdResponseWrapper.java
src/main/java/uk/gov/hmcts/sscs/domain/Subscription.java
src/main/java/uk/gov/hmcts/sscs/domain/notify/NotificationType.java
src/main/java/uk/gov/hmcts/sscs/factory/NotificationFactory.java
src/main/java/uk/gov/hmcts/sscs/factory/PersonalisationFactory.java
src/main/java/uk/gov/hmcts/sscs/personalisation/Personalisation.java
src/main/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisation.java
src/main/java/uk/gov/hmcts/sscs/service/NotificationService.java
src/main/resources/config/application.properties
src/test/java/uk/gov/hmcts/sscs/controller/NotificationControllerTest.java
src/test/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializerTest.java
src/test/java/uk/gov/hmcts/sscs/factory/NotificationFactoryTest.java
src/test/java/uk/gov/hmcts/sscs/factory/PersonalisationFactoryTest.java
src/test/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisationTest.java
src/test/java/uk/gov/hmcts/sscs/service/NotificationServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-2700
- Create a Subscription Created Notification
- Use case_details_before variable from CCD to build up oldCcdResponse

Sscs 2700 subscription created notification

---

src/main/java/uk/gov/hmcts/sscs/config/AppConstants.java
src/main/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializer.java
src/main/java/uk/gov/hmcts/sscs/factory/PersonalisationFactory.java
src/main/java/uk/gov/hmcts/sscs/personalisation/Personalisation.java
src/main/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisation.java
src/main/java/uk/gov/hmcts/sscs/service/MessageAuthenticationServiceImpl.java
src/main/resources/config/application.properties
src/test/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializerTest.java
src/test/java/uk/gov/hmcts/sscs/factory/NotificationFactoryTest.java
src/test/java/uk/gov/hmcts/sscs/factory/PersonalisationFactoryTest.java
src/test/java/uk/gov/hmcts/sscs/personalisation/PersonalisationTest.java
src/test/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisationTest.java
src/test/java/uk/gov/hmcts/sscs/service/MessageAuthenticationServiceImplTest.java

- Use Appeal Number to generate a MAC token

SSCS-2618 Generate MAC token

---

infrastructure/aat.tfvars
infrastructure/prod.tfvars
infrastructure/sandbox.tfvars

Environment variables added for aat, sandbox and prod

Variables per environments added

---

src/main/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializer.java
src/main/java/uk/gov/hmcts/sscs/domain/CcdResponse.java
src/main/java/uk/gov/hmcts/sscs/personalisation/Personalisation.java
src/main/java/uk/gov/hmcts/sscs/service/MessageAuthenticationServiceImpl.java
src/test/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializerTest.java
src/test/java/uk/gov/hmcts/sscs/factory/NotificationFactoryTest.java
src/test/java/uk/gov/hmcts/sscs/personalisation/PersonalisationTest.java
src/test/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisationTest.java
src/test/java/uk/gov/hmcts/sscs/service/MessageAuthenticationServiceImplTest.java

Add benefitType to mac token.
https://tools.hmcts.net/jira/browse/SSCS-2782

SSCS-2782[SA]:add benefit type to mac token

---

src/IntegrationTests/java/uk/gov/hmcts/sscs/tya/NotificationsIt.java
src/main/java/uk/gov/hmcts/sscs/config/AppConstants.java
src/main/java/uk/gov/hmcts/sscs/config/NotificationConfig.java
src/main/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializer.java
src/main/java/uk/gov/hmcts/sscs/domain/CcdResponse.java
src/main/java/uk/gov/hmcts/sscs/domain/Hearing.java
src/main/java/uk/gov/hmcts/sscs/domain/notify/EventType.java
src/main/java/uk/gov/hmcts/sscs/personalisation/Personalisation.java
src/main/resources/config/application.properties
src/test/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializerTest.java
src/test/java/uk/gov/hmcts/sscs/factory/NotificationFactoryTest.java
src/test/java/uk/gov/hmcts/sscs/personalisation/PersonalisationTest.java
src/test/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisationTest.java

- Add Hearings to CcdCase structure
- Add HearingBooked Notification type
- Sort hearings by latest hearing date
- Use the latest hearing to build the notification

Sscs 2703 hearing booked notification

---

src/main/java/uk/gov/hmcts/sscs/controller/RootController.java
src/test/java/uk/gov/hmcts/sscs/controller/RootControllerTest.java

- Return 200 when azure application hits the / endpoint every few seconds polluting the logs

SSCS-2899 Add Root Controller

---

src/main/java/uk/gov/hmcts/sscs/personalisation/Personalisation.java
src/test/java/uk/gov/hmcts/sscs/personalisation/PersonalisationTest.java

- Build up event personalisation data based on the actual notification to be sent rather than the latest event

SSCS-2758 Evidence received notification

---

src/main/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializer.java
src/main/java/uk/gov/hmcts/sscs/domain/Hearing.java
src/main/java/uk/gov/hmcts/sscs/personalisation/Personalisation.java
src/test/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializerTest.java
src/test/java/uk/gov/hmcts/sscs/personalisation/PersonalisationTest.java

- An hour was getting added to hearing time notifications
- Convert HearingDateTime from ZonedDateTime to LocalDateTime

Summer time hearing fix

---

src/main/java/uk/gov/hmcts/sscs/exception/AuthorisationException.java
src/main/java/uk/gov/hmcts/sscs/exception/ClientAuthorisationException.java
src/main/java/uk/gov/hmcts/sscs/exception/MacException.java
src/main/java/uk/gov/hmcts/sscs/exception/NotificationServiceException.java
src/main/java/uk/gov/hmcts/sscs/exception/TokenException.java
src/main/java/uk/gov/hmcts/sscs/service/AuthorisationService.java
src/main/java/uk/gov/hmcts/sscs/service/MessageAuthenticationServiceImpl.java
src/main/java/uk/gov/hmcts/sscs/service/NotificationService.java
src/test/java/uk/gov/hmcts/sscs/service/AuthorisationServiceTest.java

- Correctly log exceptions for app insights
- Create custom exceptions for every exception that is thrown

Fix App insights logging

---

src/IntegrationTests/resources/json/ccdCallbackResponse.json
src/main/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializer.java
src/main/java/uk/gov/hmcts/sscs/domain/CcdResponse.java
src/main/java/uk/gov/hmcts/sscs/domain/Evidence.java
src/main/java/uk/gov/hmcts/sscs/personalisation/Personalisation.java
src/test/java/uk/gov/hmcts/sscs/factory/NotificationFactoryTest.java
src/test/java/uk/gov/hmcts/sscs/personalisation/PersonalisationTest.java
src/test/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisationTest.java

- Deserialise Evidence Received details
- Create new Evidence domain object
- Store in a list and use latest to build Evidence Received notification details

SSCS-2988 Evidence Received Notification fix

---

build.gradle
src/main/java/uk/gov/hmcts/sscs/config/NotificationConfig.java
src/main/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializer.java
src/main/java/uk/gov/hmcts/sscs/domain/CcdResponse.java
src/main/java/uk/gov/hmcts/sscs/domain/CcdResponseWrapper.java
src/main/java/uk/gov/hmcts/sscs/domain/Evidence.java
src/main/java/uk/gov/hmcts/sscs/domain/Hearing.java
src/main/java/uk/gov/hmcts/sscs/domain/RegionalProcessingCenter.java
src/main/java/uk/gov/hmcts/sscs/domain/Subscription.java
src/main/java/uk/gov/hmcts/sscs/domain/notify/Destination.java
src/main/java/uk/gov/hmcts/sscs/domain/notify/Event.java
src/main/java/uk/gov/hmcts/sscs/domain/notify/Link.java
src/main/java/uk/gov/hmcts/sscs/domain/notify/Notification.java
src/main/java/uk/gov/hmcts/sscs/domain/notify/Template.java
src/main/java/uk/gov/hmcts/sscs/domain/reminder/Action.java
src/main/java/uk/gov/hmcts/sscs/domain/reminder/Reminder.java
src/main/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisation.java
src/main/java/uk/gov/hmcts/sscs/service/RegionalProcessingCenterService.java
src/test/java/uk/gov/hmcts/sscs/controller/NotificationControllerTest.java
src/test/java/uk/gov/hmcts/sscs/deserialize/CcdResponseDeserializerTest.java
src/test/java/uk/gov/hmcts/sscs/factory/NotificationFactoryTest.java
src/test/java/uk/gov/hmcts/sscs/personalisation/PersonalisationTest.java
src/test/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisationTest.java
src/test/java/uk/gov/hmcts/sscs/service/MessageAuthenticationServiceImplTest.java
src/test/java/uk/gov/hmcts/sscs/service/NotificationServiceTest.java
src/test/java/uk/gov/hmcts/sscs/service/RegionalProcessingCenterServiceTest.java
src/test/java/uk/gov/hmcts/sscs/service/ReminderServiceTest.java

- Refactor the notification service to use Lombok instead of Java boiler plate

Sscs 2993 lombok refactor

---

src/IntegrationTests/java/uk/gov/hmcts/sscs/tya/NotificationsIt.java
src/main/java/uk/gov/hmcts/sscs/factory/PersonalisationFactory.java
src/main/java/uk/gov/hmcts/sscs/personalisation/Personalisation.java
src/main/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisation.java
src/test/java/uk/gov/hmcts/sscs/factory/NotificationFactoryTest.java
src/test/java/uk/gov/hmcts/sscs/factory/PersonalisationFactoryTest.java
src/test/java/uk/gov/hmcts/sscs/personalisation/PersonalisationTest.java
src/test/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisationTest.java

- Refactor the personalisation code to autowire dependencies
- This is to try to prevent random NPE being thrown

SSCS-3010 Refactor Personalisation

---

src/IntegrationTests/java/helper/IntegrationTestHelper.java
src/IntegrationTests/java/uk/gov/hmcts/sscs/tya/HearingHoldingReminderIt.java
src/IntegrationTests/java/uk/gov/hmcts/sscs/tya/HearingReminderIt.java
src/e2e/java/uk/gov/hmcts/sscs/functional/ReminderNotificationsFunctionalTest.java
src/main/java/uk/gov/hmcts/sscs/config/AppConstants.java
src/main/java/uk/gov/hmcts/sscs/domain/notify/EventType.java
src/main/java/uk/gov/hmcts/sscs/extractor/DwpResponseReceivedDateExtractor.java
src/main/java/uk/gov/hmcts/sscs/extractor/HearingUpdateDateExtractor.java
src/main/java/uk/gov/hmcts/sscs/personalisation/Personalisation.java
src/main/java/uk/gov/hmcts/sscs/service/NotificationService.java
src/main/java/uk/gov/hmcts/sscs/service/reminder/EvidenceReminder.java
src/main/java/uk/gov/hmcts/sscs/service/reminder/HearingHoldingReminder.java
src/main/java/uk/gov/hmcts/sscs/service/reminder/HearingHoldingReminderRemover.java
src/main/java/uk/gov/hmcts/sscs/service/reminder/HearingReminder.java
src/main/java/uk/gov/hmcts/sscs/service/reminder/HearingReminderRemover.java
src/main/java/uk/gov/hmcts/sscs/service/reminder/JobGroupGenerator.java
src/main/java/uk/gov/hmcts/sscs/service/scheduler/ActionExecutor.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/sscs/extractor/DwpResponseReceivedDateExtractorTest.java
src/test/java/uk/gov/hmcts/sscs/factory/NotificationFactoryTest.java
src/test/java/uk/gov/hmcts/sscs/personalisation/PersonalisationTest.java
src/test/java/uk/gov/hmcts/sscs/personalisation/SubscriptionPersonalisationTest.java
src/test/java/uk/gov/hmcts/sscs/service/reminder/EvidenceReminderTest.java
src/test/java/uk/gov/hmcts/sscs/service/reminder/HearingHoldingReminderRemoverTest.java
src/test/java/uk/gov/hmcts/sscs/service/reminder/HearingHoldingReminderTest.java
src/test/java/uk/gov/hmcts/sscs/service/reminder/HearingReminderRemoverTest.java
src/test/java/uk/gov/hmcts/sscs/service/reminder/HearingReminderTest.java
src/test/java/uk/gov/hmcts/sscs/service/reminder/JobGroupGeneratorTest.java

https://tools.hmcts.net/jira/browse/SSCS-2790
8 week holding email/sms

SSCS-2790 Hearing holding reminders

---

infrastructure/main.tf
infrastructure/variables.tf

formatted with `terraform fmt`

Added common tags

---

infrastructure/aat.tfvars
infrastructure/preview.tfvars

This reverts commit a547e15477922f6ad1f73c3256a04f500b906755.

Revert "SSCS-3441 Update idam redirect url for sidam migration (#149)"

---

src/main/java/uk/gov/hmcts/sscs/controller/NotificationController.java

Removed s2s authentication as COH does not pass it to us.

SSCS-3543 Notify appellant of questions

---

src/e2e/java/uk/gov/hmcts/sscs/functional/ReminderNotificationsFunctionalTest.java
src/e2e/resources/hearingAdjournedCallback.json

Michael has changed the subject of the reminders which has broken the functional tests. This PR fixes this.

Sscs 3814 dynamic notifications for esa

---

src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java

Fix null pointer when trying to send notifications but the user does

---

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/NotificationsFunctionalTest.java
src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/NotificationEventType.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationValidServiceTest.java

- Send Appeal Lapsed notification for a paper case
- Start sending Appeal Lapsed SMS for oral and paper cases

[PREVIEW] SSCS-3600 Appeal lapsed paper case

---

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
src/main/java/uk/gov/hmcts/reform/sscs/TrackYourAppealNotificationsApplication.java
src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/NotificationEventType.java
src/main/resources/application.yaml

- Send evidence reminder for paper cases
- Change config to send evidence reminder 7 days after response received

[PREVIEW] SSCS-3512 Evidence Reminder paper case

---

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/CohNotificationsIt.java
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
src/main/java/uk/gov/hmcts/reform/sscs/TrackYourAppealNotificationsApplication.java
src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/OutOfHoursCalculator.java
src/main/java/uk/gov/hmcts/reform/sscs/service/scheduler/BaseActionExecutor.java
src/main/java/uk/gov/hmcts/reform/sscs/service/scheduler/CcdActionExecutor.java
src/main/java/uk/gov/hmcts/reform/sscs/service/scheduler/CohActionExecutor.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/OutOfHoursCalculatorTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/scheduler/CohActionExecutorTest.java

- Fixed trying to send coh notifications as ccd notifications.
- Fixed servers maybe running on UTC but we want to specify hours in
config as local time.

[PREVIEW] SSCS-3900 Don't send notifications out of hours

---

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/CohNotificationFunctionalTest.java
src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java
src/main/java/uk/gov/hmcts/reform/sscs/config/NotificationConfig.java
src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/NotificationEventType.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/factory/NotificationFactoryTest.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/CohPersonalisationTest.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/SubscriptionPersonalisationTest.java

Send a notification when the tribunal has issued a view.

[PREVIEW] SSCS-3548 View Issued notification

---

infrastructure/aat.tfvars
infrastructure/preview.tfvars
infrastructure/variables.tf

This is set in the Personalisation.java file

Remove /login or /sign-in from online_hearing_link env variable.

---

src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/NotificationEventType.java
src/main/resources/application.yaml

Send COR specific notifications when we set an evidence received event.

[PREVIEW] SSCS-3946 Evidence received

---

build.gradle

Fixing build pipeline

---

build.gradle

SSCS-4659 - upgrade common lib

---

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
src/main/resources/application.yaml

Add an additional line of content for appointees:
`You are receiving this update as the appointee for [appellant name]`

SSCS-4548 additional line for appointees

---

src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java

The business had asked for us to display a date 8 weeks in the future

Changed time to hear about a hearing

---

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/NotificationsFunctionalTest.java
src/e2e/resources/appointee/hearingAdjournedCallback.json
src/main/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapper.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java

hearing adjourned - appointee notification.

SSCS-4562: Appointee hearing adjourned

---

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/DwpResponseLateReminderIt.java

Test fails when it runs after 5pm and before 9am.

Fix test that fails outside 9am to 5pm

---

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/CohNotificationsIt.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/CohNotificationFunctionalTest.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/NotificationsFunctionalTest.java
src/main/resources/application.yaml

User research has not been done with SMS notifications for SMS messages
so we don't want to send them.

SSCS-5163 Remove COR SMS notifications

---

src/main/java/uk/gov/hmcts/reform/sscs/TrackYourAppealNotificationsApplication.java

SSCS-5270: Notify – filter exception threw an exception

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/factory/NotificationFactory.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/service/reminder/DwpResponseLateReminder.java
src/main/java/uk/gov/hmcts/reform/sscs/service/reminder/EvidenceReminder.java
src/main/java/uk/gov/hmcts/reform/sscs/service/reminder/HearingHoldingReminder.java
src/main/java/uk/gov/hmcts/reform/sscs/service/reminder/HearingReminder.java
src/main/java/uk/gov/hmcts/reform/sscs/service/scheduler/CohActionExecutor.java
src/test/java/uk/gov/hmcts/reform/sscs/factory/NotificationFactoryTest.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java

https://tools.hmcts.net/jira/browse/SSCS-5346
Fix: Cases with null subscription information throws exception in notifications
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

SSCS-5346 NULL Subscription

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-5219
Update sscs-common version to 0.0.155
```
[ ] Yes
[X] No
```

SSCS-5219 - update sscs-common version

---

dependency-check-suppressions.xml
src/main/java/uk/gov/hmcts/reform/sscs/service/ReminderService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/reminder/DwpResponseLateReminder.java
src/main/java/uk/gov/hmcts/reform/sscs/service/reminder/DwpResponseLateReminderRemover.java
src/main/java/uk/gov/hmcts/reform/sscs/service/reminder/EvidenceReminder.java
src/main/java/uk/gov/hmcts/reform/sscs/service/reminder/HearingHoldingReminder.java
src/main/java/uk/gov/hmcts/reform/sscs/service/reminder/HearingHoldingReminderRemover.java
src/main/java/uk/gov/hmcts/reform/sscs/service/reminder/HearingReminder.java
src/main/java/uk/gov/hmcts/reform/sscs/service/reminder/HearingReminderRemover.java
src/main/java/uk/gov/hmcts/reform/sscs/service/reminder/ReminderHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/service/ReminderServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/reminder/DwpResponseLateReminderRemoverTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/reminder/DwpResponseLateReminderTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/reminder/EvidenceReminderTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/reminder/HearingHoldingReminderRemoverTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/reminder/HearingHoldingReminderTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/reminder/HearingReminderRemoverTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/reminder/HearingReminderTest.java

SSCS-5319 Capture error from Notify (missing hearing details)

---

src/main/java/uk/gov/hmcts/reform/sscs/service/reminder/DwpResponseLateReminder.java
src/main/java/uk/gov/hmcts/reform/sscs/service/reminder/EvidenceReminder.java
src/main/java/uk/gov/hmcts/reform/sscs/service/reminder/HearingHoldingReminder.java
src/main/java/uk/gov/hmcts/reform/sscs/service/reminder/HearingReminder.java
src/test/java/uk/gov/hmcts/reform/sscs/service/reminder/DwpResponseLateReminderTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/reminder/EvidenceReminderTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/reminder/HearingHoldingReminderTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/reminder/HearingReminderTest.java

SSCS-5455 Notify - Null pointer scheduling to Quartz

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/SSCS-3937

Fix product and component variables

---

build.gradle
dependency-check-suppressions.xml

upgrade common

---

build.gradle

remove RC from master

---

infrastructure/prod.tfvars

Production emails have links to localhost in them
```
[ ] Yes
[x] No
```

added prod link

---

src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/NotificationEventType.java

send email when relisting an online hearing

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/TrackYourAppealNotificationsApplication.java

https://tools.hmcts.net/jira/browse/SSCS-5571
Update sscs-common version
```
[ ] Yes
[X] No
```

SSCS-5571 - update sscs-common version

---

infrastructure/prod.tfvars

Interloc feature flag enabled on Prod

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-4067
Update sscs-common rc version
```
[ ] Yes
[X] No
```

SSCS-4067 - sscs-common rc version

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-6161
Fix build pipeline issue
```
[ ] Yes
[X] No
```

SSCS-6161 - fix build pipeline issue

---

infrastructure/main.tf

https://github.com/hmcts/cnp-module-postgres#configuration
This needs to be added 
* subscription the subscription this module is currently being run in

fix master

---

infrastructure/prod.tfvars

Turn on direction issued letter in prod.

SSCS-6309 - Turn on direction issued letter in prod.

---

build.gradle
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/CohNotificationFunctionalTest.java

https://tools.hmcts.net/jira/browse/SSCS-6190
Go to new commons which sets a null case id
```
[ ] Yes
[x] No
```

use new common with fix for null case id

---

src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationService.java
src/test/java/uk/gov/hmcts/reform/sscs/service/SendNotificationServiceTest.java

SSCS-6345 - Appeal lodged letters should not be sent.

SSCS-6345 - Appeal lodged letters should not be sent.

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/SSCS-6378

https://tools.hmcts.net/jira/browse/SSCS-6378

---

charts/sscs-tya-notif/requirements.yaml
charts/sscs-tya-notif/values.preview.template.yaml
charts/sscs-tya-notif/values.yaml
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java

https://tools.hmcts.net/jira/browse/SSCS-6325

SSCS-6325 Handle dormant appeal notifications part 2

---

build.gradle

Revert postgresql version

---

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/DocmosisWithGovNotifyLetterFunctionalTest.java
src/e2e/resources/directionIssuedCallback.json
src/main/java/uk/gov/hmcts/reform/sscs/factory/PersonalisationFactory.java
src/main/java/uk/gov/hmcts/reform/sscs/service/BundledLetterTemplateUtil.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/factory/PersonalisationFactoryTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/BundledLetterTemplateUtilTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-6493

SSCS-6493 Add cover sheet to rep direction issued letter from docmosis

---

build.gradle
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/CohNotificationsIt.java
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/OutOfHoursIt.java
src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationSender.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationSenderTest.java

bump sscs-pdf-email common to version 1.1.5
add extra logging when saving email correspondence in dm store.

SSCS-6316 - bump sscs-pdf-email common to version 1.1.5

---

src/main/java/uk/gov/hmcts/reform/sscs/service/docmosis/PdfLetterService.java
src/test/java/uk/gov/hmcts/reform/sscs/service/docmosis/PdfLetterServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-6467
Change address constants for docmosis templates to match Notify templates
```
[ ] Yes
[X] No
```

SSCS-6467 - docmosis address constants

---

src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java

https://tools.hmcts.net/jira/browse/SSCS-6554

SSCS-6554 Universal Credit changes for notifications

---

build.gradle
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceForSubscriptionUpdatedTest.java
src/main/java/uk/gov/hmcts/reform/sscs/domain/NotifyResponse.java
src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationSender.java
src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationSenderTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-6431

SSCS-6431 Store SMSs sent out from Gov Notify

---

build.gradle
charts/sscs-tya-notif/requirements.yaml
dependency-check-suppressions.xml

try no suppression

---

Jenkinsfile_CNP

remove aks

---

Jenkinsfile_CNP
build.gradle
charts/sscs-tya-notif/values.preview.template.yaml
charts/sscs-tya-notif/values.yaml
dependency-check-suppressions.xml
infrastructure/main.tf
infrastructure/variables.tf
src/main/java/uk/gov/hmcts/reform/sscs/callback/CallbackDispatcher.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/CallbackHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/NotificationEventType.java
src/main/java/uk/gov/hmcts/reform/sscs/servicebus/TopicConsumer.java
src/main/java/uk/gov/hmcts/reform/sscs/servicebus/messaging/JmsErrorHandler.java
src/main/java/uk/gov/hmcts/reform/sscs/servicebus/messaging/MessagingConfig.java
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml
src/test/java/uk/gov/hmcts/reform/sscs/callback/CallbackDispatcherTest.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/HandlerHelper.java
src/test/java/uk/gov/hmcts/reform/sscs/servicebus/TopicConsumerTest.java

Currently only filtering `dwpUploadResponse` event, but there is not notifications setup for it. This will be done in another PR.

SSCS-5210 - add notifications subscription

---

build.gradle
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/CohNotificationsIt.java
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/OutOfHoursIt.java
src/e2e/resources/representative/appealWithdrawnCallback.json
src/e2e/resources/representative/hearingBookedCallback.json
src/main/java/uk/gov/hmcts/reform/sscs/TrackYourAppealNotificationsApplication.java
src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationSender.java
src/main/java/uk/gov/hmcts/reform/sscs/service/SaveLetterCorrespondenceAsyncService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationSenderTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/SaveLetterCorrespondenceAsyncServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/SendNotificationServiceTest.java

Store Gov.Notify Letters in CCD

SSCS-6389 StoreGovNotifyLetters

---

build.gradle

Sscs 6624 tya hearing fix

---

dependency-check-suppressions.xml

no fix available, we can't upgrade this library as yet.

suppress until end of the month

---

dependency-check-suppressions.xml
src/main/resources/bootstrap.yaml

Use env vars as in application.yaml

---

src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java

https://tools.hmcts.net/jira/browse/SSCS-6764

SSCS-6764 Use CCD ID when created in gaps from field is readyToList

---

dependency-check-suppressions.xml

Suppress dependency check for quartz issue for a month as there is no

---

build.gradle
dependency-check-suppressions.xml

fix for CVE-2019-13990

---

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationService.java

https://tools.hmcts.net/jira/browse/SSCS-6931

SSCS-6931 Send Direction issued when dormant

---

build.gradle
dependency-check-suppressions.xml
src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/NotificationEventType.java
src/main/resources/application.yaml

sscs6798
change lapse eveent id
```
[ ] Yes
[x] No
```

6798 changed event id

---

build.gradle
charts/sscs-tya-notif/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/SSCS-6836

SSCS-6836 Add missing fields to java model

---

src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java
src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationService.java
src/test/java/uk/gov/hmcts/reform/sscs/service/SendNotificationServiceTest.java

SSCS-6965 Notification – Letters sent via Notify don’t have name

---

build.gradle
infrastructure/main.tf
src/main/java/uk/gov/hmcts/reform/sscs/TrackYourAppealNotificationsApplication.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/SSCS-7088

SSCS-7088 Use notifications sent event

---

src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/reminder/AllReminderRemover.java
src/main/java/uk/gov/hmcts/reform/sscs/service/scheduler/BaseActionExecutor.java
src/test/java/uk/gov/hmcts/reform/sscs/service/reminder/AllReminderRemoverTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/scheduler/CcdActionExecutorTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/scheduler/CohActionExecutorTest.java

https://tools.hmcts.net/jira/browse/SSCS-7053

SSCS-7053 Remove reminders when appeal dormant

---

Jenkinsfile_CNP
build.gradle
config/checkstyle/checkstyle.xml
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
src/main/java/uk/gov/hmcts/reform/sscs/config/DocmosisTemplatesConfig.java
src/main/java/uk/gov/hmcts/reform/sscs/config/NotificationBlacklist.java
src/main/java/uk/gov/hmcts/reform/sscs/service/LetterUtils.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationUtilsTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/reminder/EvidenceReminderTest.java

Updated check style version

---

build.gradle

Reverts hmcts/sscs-track-your-appeal-notifications#827

Revert "Bump postgresql from 42.2.2 to 42.2.10"

---

Jenkinsfile_CNP

DNS Swap to AKS Prod

---

build.gradle
charts/sscs-tya-notif/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/SSCS-7308

SSCS-7308 Pick Latest direction or decision notices

---

build.gradle
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceBase.java
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/CohNotificationsIt.java
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/HearingReminderIt.java
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/OutOfHoursIt.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ReminderNotificationsFunctionalTest.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/NotificationsFunctionalTest.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/WithRepresentativePersonalisationTest.java
src/e2e/resources/application_e2e.yaml
src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-7374

SSCS-7374 Stop hearing booked and hearing reminders due to coronavirus

---

src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-7382

SSCS-7382 Send notification for new cases

---

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationValidService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/SendNotificationServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-7397

SSCS-7397 Docmosis dwp upload response letter

---

src/main/java/uk/gov/hmcts/reform/sscs/factory/NotificationFactory.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/test/java/uk/gov/hmcts/reform/sscs/factory/NotificationFactoryTest.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java

https://tools.hmcts.net/jira/browse/SSCS-7408

SSCS-7408 Handle empty benefit types

---

src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationService.java

SSCS-7412: Notifications – Bundled letter is not sent due to exception

---

build.gradle
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/SSCS-7477

SSCS-7477 Use new HMCTS logo for letters

---

src/main/java/uk/gov/hmcts/reform/sscs/service/OutOfHoursCalculator.java
src/test/java/uk/gov/hmcts/reform/sscs/service/OutOfHoursCalculatorTest.java

https://tools.hmcts.net/jira/browse/SSCS-7472

SSCS-7472 Pick a random minute to schedule reminders

---

README.md
build.gradle
charts/sscs-tya-notif/Chart.yaml
charts/sscs-tya-notif/values.yaml
infrastructure/main.tf
src/main/java/uk/gov/hmcts/reform/sscs/config/LegacyFlywayAutoConfiguration.java

Sscs 7333 upgrade db

---

charts/sscs-tya-notif/Chart.yaml
charts/sscs-tya-notif/values.preview.template.yaml
charts/sscs-tya-notif/values.yaml
src/main/resources/application.yaml

Disable DB migration on startup and enable only on Preview

---

build.gradle

Fixed apache tika vulnerabilities

---

dependency-check-suppressions.xml
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/WithRepresentativePersonalisation.java
src/main/java/uk/gov/hmcts/reform/sscs/service/LetterUtils.java
src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationHelper.java
src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/docmosis/PdfLetterService.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/WithRepresentativePersonalisationTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/LetterUtilsTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/SendNotificationServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/docmosis/PdfLetterServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-7413

SSCS-7413 Handle undefined rep names

---

charts/sscs-tya-notif/Chart.yaml
charts/sscs-tya-notif/values.yaml

Migrate TYA Unsubscribe link to MYA

SSCS-7130 - Migrate TYA Unsubscribe link to MYA

---

.github/renovate.json
charts/sscs-tya-notif/Chart.yaml
charts/sscs-tya-notif/requirements.yaml

SSCS-7587
Upgrade java chart. 
Add renovate

SSCS-7587 - Upgrade java chart. Add renovate

---

README.md
build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/controller/test/smoke/SmokeController.java
src/main/java/uk/gov/hmcts/reform/sscs/service/LetterUtils.java
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml

SCSS 7575 - Library Pipeline for Pact Testing

---

build.gradle
dependency-check-suppressions.xml
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/SyaAppealCreatedAndReceivedPersonalisation.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/SyaAppealCreatedAndReceivedPersonalisationTest.java

SSCS-7756 - Reasons for Appealing switching

SSCS-7756 - Reasons for Appealing switching

---

build.gradle

fix security vulnerabilities

---

src/main/java/uk/gov/hmcts/reform/sscs/personalisation/SyaAppealCreatedAndReceivedPersonalisation.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/SyaAppealCreatedAndReceivedPersonalisationTest.java

https://tools.hmcts.net/jira/browse/WLA-636
Corrected Welsh translator date formatter.
```
[ ] Yes
[ x] No
```

WLA-636: Welsh formatter updated with correct date formatter.

---

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-7790
Ensuring handling is implemented/tested for issue adjournment reissue
```
[ ] Yes
[x] No
```

SSCS-7790 Adding Adjourn Case Reissue Handling

---

dependency-check-suppressions.xml

suppress CVE-2020-15824 for a month

suppress CVE-2020-15824 for a month

---

build.gradle

Reverts hmcts/sscs-track-your-appeal-notifications#1102

Revert "Bump postgresql from 42.2.14 to 42.2.15"

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-7535
SSCS-7535 Up commons for isScottish
```
[ ] Yes
[ ] No
```

SSCS-7535 Up commons for isScottish

---

audit.json

added urls

---

security.sh

updated severity from High to Medium

---

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/main/resources/application.yaml

SSCS-8031 & SSCS-8032 - Grant/Refuse time extension letter

SSCS-8031 & SSCS-8032 - Grant/Refuse time extension letter

---

dependency-check-suppressions.xml

suppress kotlin library version

---

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/JointPartyFunctionalTest.java
src/e2e/resources/jointParty/hearingPostponedCallback.json
src/main/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapper.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java

https://tools.hmcts.net/jira/browse/SSCS-7942
Merge SSCS-7938 first, followed by SSCS-7943 followed by this.

Sscs 7942 joint party hearing postponed

---

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ReminderNotificationsFunctionalTest.java

Reverts hmcts/sscs-track-your-appeal-notifications#1181

Revert "Temporarily ignore the failing test"

---

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ReminderNotificationsFunctionalTest.java

Unignore a reminder test

---

src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java
src/main/java/uk/gov/hmcts/reform/sscs/config/properties/EvidenceProperties.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/factory/NotificationFactoryTest.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/SubscriptionPersonalisationTest.java

WLA-731: Parameterize Welsh phone number for notifications

---

build.gradle

WLA-735: Upgrade commons 3.4.69

---

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/DocmosisWithGovNotifyLetterFunctionalTest.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/JointPartyFunctionalTest.java
src/e2e/resources/directionIssuedProvideInformationCallback.json
src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java
src/main/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapper.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java
src/test/resources/json/ccdResponseWithJointParty.json

https://tools.hmcts.net/jira/browse/SSCS-7974
Sends a letter
```
[ ] Yes
[x] No
```

Sscs 7974 direction provide info

---

build.gradle
src/IntegrationTests/java/helper/IntegrationTestHelper.java
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationItForReviewConfidentialityRequestTest.java
src/main/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapper.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java

https://tools.hmcts.net/jira/browse/SSCS-7999
https://tools.hmcts.net/jira/browse/SSCS-8003
https://tools.hmcts.net/jira/browse/SSCS-8005
```
[ ] Yes
[x] No
```

Sscs 8003 confidentiality request v2

---

src/e2e/resources/jointParty/reviewConfidentialityRequestCallback.json
src/e2e/resources/reviewConfidentialityRequestCallback.json

https://tools.hmcts.net/jira/browse/SSCS-8003
https://tools.hmcts.net/jira/browse/SSCS-8005
https://tools.hmcts.net/jira/browse/SSCS-7999
Fixing json for functional test
```
[ ] Yes
[x] No
```

SSCS-8003 Fixing functional test for confidentiality field change

---

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/WelshNotificationsFunctionalTest.java
src/e2e/resources/hearingPostponedCallbackWelsh.json
src/main/resources/application.yaml

SSCS-8163 - Hearing postponed Joint Party Welsh

SSCS-8163 - Hearing postponed Joint Party Welsh

---

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/WelshNotificationsFunctionalTest.java
src/e2e/resources/oral-appealDormantCallbackWelsh.json
src/main/resources/application.yaml

SSCS-8164 - JP (Welsh) - Decision made (attended hearing)

SSCS-8164 - JP (Welsh) - Decision made (attended hearing)

---

src/main/resources/application.yaml

reset notifications end hour back to 17

---

src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java

https://tools.hmcts.net/jira/browse/SSCS-8114
```
[ ] Yes
[ ] No
```

SSCS-8114 Set Phone from RPC unless not present

---

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/NotificationsFunctionalTest.java
src/e2e/resources/oral-dwpUploadResponseCallback.json
src/e2e/resources/paper-dwpUploadResponseCallback.json

https://tools.hmcts.net/jira/browse/SSCS-8314

SSCS-8314 Add DWP upload response functional tests

---

dependency-check-suppressions.xml

Extending the suppressed date

---

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
src/main/resources/application.yaml

SSCS-8260 - Appellant, Appointee and Representative (Welsh) - Information request
Welsh Translation for Appellant/Appointee and Representative

SSCS-8260 - Appellant, Appointee and Representative (Welsh) - Information request

---

src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java

Added refuse urgent hearing notification and updated tests
Jira link: [https://tools.hmcts.net/jira/browse/SSCS-7988](url)

Added refuse urgent hearing notification

---

dependency-check-suppressions.xml

Fixing for nightly tests
```
[ ] Yes
[ ] No
```

Suppress for nightly tests

---

build.gradle

fixed the dependency check

---

dependency-check-suppressions.xml

fixed the depedency check

---

src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/scheduler/BaseActionExecutor.java

SSCS-8118: Added extra logs

---

src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-8230
```
[ ] Yes
[ ] No
```

SSCS-8230: Adjournment notice - Welsh translation

---

build.gradle

fix for CVE-2020-17521

---

build.gradle

fix for CVE-2020-15824

---

src/main/java/uk/gov/hmcts/reform/sscs/service/SaveLetterCorrespondenceAsyncService.java
src/main/resources/application.yaml

SSCS-8571: Reps letter is not stored on Notification tab

---

build.gradle

SSCS-8118: Notifications – Multiple notifications are being sent out

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/SSCS-8573
```
[ ] Yes
[ ] No
```

SSCS-8573: White list scottish postcode for local testing

---

build.gradle
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/AbstractFunctionalTest.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/AdminAppealWithdrawnNotificationsTest.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/NotificationsFunctionalTest.java
src/e2e/resources/appealReceivedAppellantReasonableAdjustmentCallback.json
src/e2e/resources/appealReceivedAppellantRepReasonableAdjustmentCallback.json
src/main/java/uk/gov/hmcts/reform/sscs/service/LetterUtils.java
src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationSender.java
src/main/java/uk/gov/hmcts/reform/sscs/service/SaveLetterCorrespondenceAsyncService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationService.java
src/test/java/uk/gov/hmcts/reform/sscs/service/LetterUtilsTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationSenderTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/SaveLetterCorrespondenceAsyncServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/SendNotificationServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-8494
https://tools.hmcts.net/jira/browse/SSCS-8594
```
[ ] Yes
[ ] No
```

Sscs 8494: Notification Services - Stop Letters with 'Alternative Letter Format' Flag

---

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/handlers/AdminAppealWithdrawnNotificationsTest.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/NotificationsFunctionalTest.java

https://tools.hmcts.net/jira/browse/SSCS-8574
```
[ ] Yes
[ ] No
```

SSCS-8574: Look at Jenkins pipeline reliability

---

build.gradle
dependency-check-suppressions.xml

Suppress kotlin lib dependency check

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/TrackYourAppealNotificationsApplication.java

SSCS-8684 - Upgrade Idam Client Only

SSCS-8684 - Upgrade Idam Client Only

---

charts/sscs-tya-notif/Chart.yaml
charts/sscs-tya-notif/values.yaml

https://tools.hmcts.net/jira/browse/SSCS-8757
new urls
```
[ ] Yes
[x] No
```

sscs-8757 new docmosis urls for staging

---

build.gradle
dependency-check-suppressions.xml
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
src/main/java/uk/gov/hmcts/reform/sscs/config/AppealHearingType.java
src/main/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapper.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/main/java/uk/gov/hmcts/reform/sscs/service/ReminderService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/ReminderServiceTest.java

SSCS-8138 - Remove COR templates

SSCS-8138 - Remove COR templates

---

build.gradle

fixed the dependnecy check

---

src/main/resources/application.yaml

Updated pdf service to point to docmosis-aat url while running local

---

build.gradle

upgrade tomcat version to fix depedency check

---

src/main/java/uk/gov/hmcts/reform/sscs/exception/NotificationServiceException.java
src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationHandlerTest.java

SSCS-8856 - Enhance the logs when Notify comes back with an error

SSCS-8856 - Enhance the logs when Notify comes back with an error

---

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/NotificationsFunctionalTest.java
src/e2e/resources/paper/responseReceived/dla-paper-responseReceivedCallback.json
src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java

SSCS-8878 DLA Panel Composition

---

build.gradle

revert SSCS-8894

---

build.gradle
dependency-check-suppressions.xml

SSCS-9046 - fix DC failures

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/utils/GetAllTemplatesFromNotify.java

https://tools.hmcts.net/jira/browse/SSCS-9045
A class to talk to Notify and get templates
```
[ ] Yes
[x] No
```

sscs 9045 class to pull templates

---

src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java

SSCS-9071 - add personalisation fields

SSCS-9071 - add personalisation fields

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-9064
```
[ ] Yes
[ x] No
```

SSCS-9064: Use sscs-job-scheduler jitpack jar

---

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ReminderNotificationsFunctionalTest.java

Reverts hmcts/sscs-track-your-appeal-notifications#1585

Revert "Ignore failing test"

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java

https://tools.hmcts.net/jira/browse/SSCS-8899
Added a panel for attendance allowance
```
[ ] Yes
[x] No
```

sscs 8899 added attendance allowance test and config

---

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ReminderNotificationsFunctionalTest.java

added ignore to one of the reminder notification functional tests

added ignore to one of the reminder notification functional tests

---

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ReminderNotificationsFunctionalTest.java

Reverts hmcts/sscs-track-your-appeal-notifications#1587

Revert "added ignore to one of the reminder notification functional tests"

---

dependency-check-suppressions.xml

dependency-check-suppressions

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-9066
Finish move to jitpack
```
[ ] Yes
[x] No
```

sscs 9066 jitpack move

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-9066
Move to release
```
[ ] Yes
[x] No
```

Sscs 9066 jitpack

---

build.gradle
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/NotificationsFunctionalTest.java
src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java

SSCS-9154 - Carer's Allowance - Panel List for Notification Content

SSCS-9154 - Carer's Allowance - Panel List for Notification Content

---

audit.json

Ticket raised here to address this warning https://tools.hmcts.net/jira/browse/SSCS-9196
```
[ ] Yes
[ ] No
```

Suppress sec warnings

---

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/NotificationsFunctionalTest.java

https://tools.hmcts.net/jira/browse/SSCS-9197

SSCS-9197 Remove benefit word from notifications

---

build.gradle
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java

https://tools.hmcts.net/jira/browse/SSCS-8906

SSCS-8906 Bereavement benefit DWP mappings

---

build.gradle

SSCS-9122 upgrade common

---

src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandler.java
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandlerTest.java

SSCS-9286 - handle null events

SSCS-9286 - handle null events

---

build.gradle
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/DocmosisWithGovNotifyLetterFunctionalTest.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/WelshNotificationsFunctionalTest.java
src/e2e/resources/requestInfoIncompleteApplicationCallback.json
src/e2e/resources/requestInfoIncompleteApplicationCallbackWelsh.json
src/main/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapper.java
src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationHandlerTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/SendNotificationServiceTest.java
src/test/resources/json/ccdResponse_requestInfoIncomplete.json
src/test/resources/json/ccdResponse_requestInfoIncompleteAppellant.json

https://tools.hmcts.net/jira/browse/SSCS-9151

SSCS-9151 Issue generic letter to specified party

---

dependency-check-suppressions.xml

suppress CVE-2021-33813

---

build.gradle
src/test/java/uk/gov/hmcts/reform/sscs/service/scheduler/CcdActionExecutorTest.java

https://tools.hmcts.net/jira/browse/SSCS-9305

SSCS-9305 Refactor after moving deprecated fields

---

build.gradle

CVE-2021-31811 - fix

---

dependency-check-suppressions.xml

Suppress for one more month

---

src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java

https://tools.hmcts.net/jira/browse/SSCS-9338

SSCS-9338 Translation for welsh word for joint

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/TrackYourAppealNotificationsApplication.java
src/main/resources/application.yaml

SSCS-9420 - Update doc store client

SSCS-9420 - Update doc store client

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/factory/NotificationFactory.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java

SSCS-9341 BenefitType not found

SSCS-9341 BenefitType not found

---

Jenkinsfile_nightly
build.gradle
config/fortify-client.properties
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/SSCS-9381
The changes are in this PR but the same are implemented on nightly branch
```
[ ] Yes
[ x] No
```

SSCS-9381:Enable fortify scan for nightly build

---

build.gradle

fix for CVE-2021-28170

---

Jenkinsfile_nightly
build.gradle

https://tools.hmcts.net/jira/browse/SSCS-9273
Same change runs on nightly-dev branch
```
[ ] Yes
[ x] No
```

SSCS-9273:Enable mutation test

---

src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationSender.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationSenderTest.java

SSCS-9553 - Wrong date used for saving notification

SSCS-9553 - Wrong date used for saving notification

---

build.gradle
src/test/java/uk/gov/hmcts/reform/sscs/servicebus/TopicConsumerTest.java

https://tools.hmcts.net/jira/browse/SSCS-9429

SSCS-9429 Deserialize case type id

---

build.gradle

Sscs 9750 amend gaps venue

---

dependency-check-suppressions.xml

Suppress failed vulnerabilities

---

build.gradle
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/JointPartyFunctionalTest.java
src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/WelshNotificationsFunctionalTest.java

SSCS-9777: Tribunals / Common – Change the document ordering

---

dependency-check-suppressions.xml
src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java
src/main/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapper.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/WithRepresentativePersonalisation.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java

https://tools.hmcts.net/jira/browse/SSCS-9780
Added a flag and updated templates for other parties
```
[ ] Yes
[x] No
```

Sscs 9780 other party letters

---

build.gradle
src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java

https://tools.hmcts.net/jira/browse/SSCS-9889

Sscs 9889 other party added notification sscs5

---

charts/sscs-tya-notif/Chart.yaml

https://tools.hmcts.net/jira/browse/SSCS-10137
```
[ ] Yes
[X] No
```

upgrade helms chart

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-10070
Update sscs-common version
```
[ ] Yes
[ ] No
```

Update sscs-common version

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-10234
version update is applied for the security vulnerability
```
[X] Yes
[ ] No
```

"SSCS-10234-netflix version updated

---

charts/sscs-tya-notif/Chart.yaml

Bump java and chart version

---

charts/sscs-tya-notif/Chart.yaml

https://tools.hmcts.net/jira/browse/SSCS-10236
```
[ ] Yes
[X] No
```

SSCS-10236 updating helm chart version

---

dependency-check-suppressions.xml

suppress dc warning

---

build.gradle

SSCS-9872-update-commons-version

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10280
```
[ ] Yes
[X] No
```

SSCS-10280: suppressing dependencies

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10297
```
[ ] Yes
[X] No
```

SSCS-10297: suppressing dependencies

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-10318
```
[ ] Yes
[x] No
```

SSCS-10318: updating commons version to 4.6.48

---

build.gradle
dependency-check-suppressions.xml

Update SSCS Commons to 4.7.0

---

build.gradle

SSCS Commons 4.7.1 Upgrade

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10376
Fix nightly build
```
[ ] Yes
[x ] No
```

SSCS-10376-Fix-Nightly-Build: supressions and upgrades

---

build.gradle
dependency-check-suppressions.xml
src/main/java/uk/gov/hmcts/reform/sscs/config/SwaggerConfiguration.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/controller/ReminderTestController.java

https://tools.hmcts.net/jira/browse/SSCS-10376
```
[ ] Yes
[ ] No
```

SSCS-10376 Fix build

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10387
```
[ ] Yes
[x] No
```

SSCS-10387 Update Commons

---

build.gradle
dependency-check-suppressions.xml
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceBase.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/main/java/uk/gov/hmcts/reform/sscs/service/LetterUtils.java
src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationUtils.java
src/test/java/uk/gov/hmcts/reform/sscs/SscsCaseDataUtils.java
src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/LetterUtilsTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationUtilsTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/SendNotificationServiceTest.java

https://tools.hmcts.net/jira/browse/SSCS-10388
```
[x] Yes
[ ] No
```

SSCS-10388 Update Commons

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/SSCS-10443
tagging added to Azure resources.
```
[ ] Yes
[X] No
```

Sscs 10443 azure tagging appeal notifications

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10503
```
[ ] Yes
[X] No
```

SSCS-10503: Fix Nightly Build

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-10355
bump sscs common version
```
[ ] Yes
[ ] No
```

sscs-10355 bump sscs common version

---

build.gradle

https://tools.hmcts.net/jira/browse/SSCS-10555
```
[ ] Yes
[X] No
```

SSCS-10555: Upgrading Spring Core

---

build.gradle

update commons version

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10445
```
[ ] Yes
[x] No
```

SSCS-10445 Commons Bump

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10648
```
[ ] Yes
[X] No
```

SSCS-10468: Update dependency suppressions

---

build.gradle

Commons Automation

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10746
Update tika core to 2.4.1
```
[ ] Yes
[x] No
```

SSCS-10746-tika-cve-fix : update tike core

---

charts/sscs-tya-notif/Chart.yaml
charts/sscs-tya-notif/values.preview.template.yaml

sscsBaseChartUpdate-Java401
```
[ ] Yes
[ ] No
```

sscsBaseChartUpdate-Java401

---

dependency-check-suppressions.xml

extend dep suppression

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10805
```
[ ] Yes
[ ] No
```

SSCS-10805-jar-version-update

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-9874
```
[ ] Yes
[ ] No
```

sscs-9874-common-version-update

---

build.gradle
src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandlerTest.java

https://tools.hmcts.net/jira/browse/SSCS-10882
```
[ ] Yes
[x] No
```

SSCS-10882 Fixing Conflicting IDs

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10968
```
[ ] Yes
[ ] No
```

SSCS-10968 cve suppression

---

.gitignore
README.md
bin/render-docmosis-template.ps1
bin/render-docmosis-template.sh
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10887
```
[ ] Yes
[x] No
```

SSCS-10887 Tool for Rendering Docmosis Letters

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-10985
```
[ ] Yes
[x] No
```

SSCS-10985 CVE Fix Commons Bump

---

.gitignore
infrastructure/main.tf

SSCS-11008
Add content type and tags to secrets
```
[ ] Yes
[ x ] No
```

SSCS-11008 - Add content type and tags to secrets

---

Jenkinsfile_CNP
Jenkinsfile_nightly
charts/sscs-tya-notif/Chart.yaml
charts/sscs-tya-notif/values.preview.template.yaml
charts/sscs-tya-notif/values.yaml
src/main/resources/bootstrap.yaml

https://tools.hmcts.net/jira/browse/SSCS-10924

SSCS-10924 Use tf managed secret.

---

build.gradle
dependency-check-suppressions.xml

To fix CVE-2022-42252
```
[ ] Yes
[ x ] No
```

tomcat to 9.0.68

---

infrastructure/variables.tf

SSCS-11447 : Removed ilbIp variable from terraform

---

build.gradle
dependency-check-suppressions.xml

Upgrade and suppress

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

renovate upgrade

---

build.gradle

renovate 23-03-23

---

build.gradle

CVE-fix-05.04.23
```
[ ] Yes
[x] No
```

CVE-fix-05.04.23

---

Jenkinsfile_nightly

FortifyScan-afterSuccess
```
[ ] Yes
[x] No
```

FortifyScan-afterSuccess

---

audit.json

Security ignoring
```
[ ] Yes
[x] No
```

Removal security sh file

---

audit.json

Removal of security.sh
```
[ ] Yes
[x] No
```

Removal of security.sh

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/SSCS-11579
CVE fix - jackson-databind
```
[ ] Yes
[x] No
```

SSCS-11579 - CVE fix

---

build.gradle
dependency-check-suppressions.xml
src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java
src/main/java/uk/gov/hmcts/reform/sscs/config/PersonalisationMappingConstants.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java

SSCS-11381 - add new constant

---

dependency-check-suppressions.xml

CVE Suppression - 12.06.2023
```
[ ] Yes
[x] No
```

CVE Suppression - 12.06.2023

---

dependency-check-suppressions.xml

CVE Fix 27.06.23
```
[ ] Yes
[x] No
```

CVE Fix.27.06.23

---

build.gradle
dependency-check-suppressions.xml

CVE Fix - 03.07.23
```
[ ] Yes
[x] No
```

CVE Fix - 03.07.23

---

build.gradle
dependency-check-suppressions.xml

Gradle dependencies and suppressions cleanup
```
[ ] Yes
[x] No
```

Gradle dependencies and suppressions cleanup

---

build.gradle
dependency-check-suppressions.xml

Jackson revert

---

src/test/java/uk/gov/hmcts/reform/sscs/service/scheduler/CcdActionExecutorTest.java

Added test to verify deserialisation of localdatetime
```
[ ] Yes
[x] No
```

Added test to verify deserialisation of localdatetime

---

dependency-check-suppressions.xml

CVE Fix - 31.07.2023
```
[ ] Yes
[x] No
```

CVE Fix - 31.07.2023

---

build.gradle
dependency-check-suppressions.xml

CVE Fix and suppression - 04.08.2023
```
[ ] Yes
[x] No
```

CVE Fix and suppression - 04.08.2023

---

audit.json

https://tools.hmcts.net/jira/browse/SSCSCI-12
Fix audit issue
```
[ ] Yes
[X ] No
```

security-fix-12092023

---

build.gradle
src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/BundledNotificationsConfigTestIt.java
src/main/java/uk/gov/hmcts/reform/sscs/config/NotificationEventTypeLists.java
src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/NotificationEventType.java
src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
src/test/java/uk/gov/hmcts/reform/sscs/service/SendNotificationServiceTest.java

SSCS-10581
```
[ ] Yes
[ ] No
```

TYA: add adminCorrectionHeader

---

build.gradle
charts/sscs-tya-notif/Chart.yaml
dependency-check-suppressions.xml

Update suppressions
Update Java helm version

CVE Fix 06.11.2023

---

infrastructure/main.tf
infrastructure/state.tf
infrastructure/variables.tf

- https://tools.hmcts.net/jira/browse/SSCSCI-514
- add Postgres flexible server terraform configuration

SSCSCI-514: add postgres flexible server terraform config

---

infrastructure/main.tf

[DTSPO-15872](https://tools.hmcts.net/jira/browse/DTSPO-15872)

DTSPO-15872 Fix DB config for AAD access

---

dependency-check-suppressions.xml

SSCS -Update suppressions

---

dependency-check-suppressions.xml

SSCS- Update Suppressions

---

build.gradle

dependency check upgrade to 9.0.6

dependency check upgrade

---

dependency-check-suppressions.xml

CVE Fix - 22.01.2024

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/SSCSCI-517
Enable user permission script to run

SSCSCI-517: Setup Access Reader

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/SSCSCI-662
remove old database

SSCSCI-662

---

dependency-check-suppressions.xml

Update suppression date

---

dependency-check-suppressions.xml

Added new CVE to suppressions: CVE-2024-25710

Updated suppressions

---

build.gradle
charts/sscs-tya-notif/Chart.yaml
charts/sscs-tya-notif/values.yaml
src/main/java/uk/gov/hmcts/reform/sscs/service/SaveCorrespondenceAsyncService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/service/SaveCorrespondenceAsyncServiceTest.java

https://tools.hmcts.net/jira/browse/SSCSSI-6

Use new helper method which retrieves data from CCD DB and updates correspondence instead of in memory case data

---

build.gradle
charts/sscs-tya-notif/Chart.yaml
charts/sscs-tya-notif/values.yaml
src/main/java/uk/gov/hmcts/reform/sscs/service/SaveCorrespondenceAsyncService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/service/SaveCorrespondenceAsyncServiceTest.java

https://tools.hmcts.net/jira/browse/SSCSSI-28
Use new pdf-email-common helper methods

Use new helper methods to upload letter correspondence to CCD

---

src/main/java/uk/gov/hmcts/reform/sscs/TrackYourAppealNotificationsApplication.java
src/main/java/uk/gov/hmcts/reform/sscs/service/scheduler/BaseActionExecutor.java
src/main/java/uk/gov/hmcts/reform/sscs/service/scheduler/CcdActionExecutor.java
src/test/java/uk/gov/hmcts/reform/sscs/service/scheduler/CcdActionExecutorTest.java

https://tools.hmcts.net/jira/browse/SSCSSI-32

Use update case v2 to trigger notification sent for scheduled reminders

---

src/main/java/uk/gov/hmcts/reform/sscs/config/NotificationEventTypeLists.java

https://tools.hmcts.net/jira/browse/SSCS-12241
Addded 'request info from party' to dormant state approved list

Addded 'request info from party' to dormant state approved list

---

charts/sscs-tya-notif/Chart.yaml
charts/sscs-tya-notif/values.yaml
src/main/java/uk/gov/hmcts/reform/sscs/service/SaveCorrespondenceAsyncService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/sscs/service/SaveCorrespondenceAsyncServiceTest.java

https://tools.hmcts.net/jira/browse/SSCSSI-6
https://tools.hmcts.net/jira/browse/SSCSSI-28
Cleanup feature toggles from tya SaveCorrespondenceAsyncService

Remove feature toggles from tya correspondence document update

---

src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java

partial revert of SSCS-12233

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/SSCSCI-874
Updated suppression date

SSCSCI-874 Update suppression date

---

infrastructure/state.tf

Overhang on
https://tools.hmcts.net/jira/browse/SSCSCI-874

SSCSCI-874:  Azure resource manager tf  fix

---

charts/sscs-tya-notif/Chart.yaml
charts/sscs-tya-notif/values.yaml

https://tools.hmcts.net/jira/browse/SSCSCI-499

SSCSCI-499: upgrade java chart

---

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceForSubscriptionUpdatedTest.java
src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java

https://tools.hmcts.net/jira/browse/SSCSCI-770
Remove resend last notification so that only subscription notifications should be sent when MYA subscription is updated

SSCSCI-770 - Remove resend last notification

---

src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationValidService.java
src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java

SSCS-12230 - Restrict Hearing Booked

---

src/main/java/uk/gov/hmcts/reform/sscs/servicebus/messaging/MessagingConfig.java

Updated SSLContext protocol to TSL

Fortify issue fix

---

build.gradle

See [SSCSCI-1004](https://tools.hmcts.net/jira/browse/SSCSCI-1004)
- common version bump to update huddersfield venue address

common version bump to update huddersfield venue address
